### ISSUE TITLE
[Bug] Using deprecated APIs

### ISSUE THREAD

**Issue by zerebos** [SheiylaDev/ChannelsBadges#1]
Hi there, your plugin was denied with reason:
> The plugin is using all the deprecated APIs, please see the docs and update to the newer versions. After that please resubmit, the plugin looks great otherwise!

Please take a look at the documentation for the API and make sure you are using the current methods instead of the old ones. (i.e. use `BdApi.Webpack` over `BdApi.findModuleByProps` or `BdApi.Data` over `BdApi.loadData`).

Here is the plugin guide: https://docs.betterdiscord.app/plugins/
Here is the api reference: https://docs.betterdiscord.app/api/bdapi

Other than that, the plugin looks great! I'd love to see this updated and resubmitted. Feel free to ping me (Zerebos) once you do and I'll be sure to give it a priority review.

**Comment by rauenzi** [comment]
New update looks good, only thing I would say is to remove these:
```js
    getName() { return "ChannelsBadges"; }
    getDescription() { return "Add Voice | Forum | Nsfw | Rule | Ads badges to channels."; }
    getVersion() { return "1.1.0"; }
    getAuthor() { return "Sheiylanie"; }
```

Those are long deprecated and it's just a duplication of the information in the meta comment. BTW the info in the meta comment is passed to the `constructor` of the plugin so you can still access the information programmatically.
```js
class MyPlugin {
    constructor(meta) {
        this.meta = meta;
    }
    
    someOtherFunc() {
        console.log(this.meta.version);
    }
}
```

I'll still be approving the plugin, but just something to note!
