### ISSUE TITLE
icon issue

### ISSUE THREAD

**Issue by AcesGamingUK** [SheiylaDev/ChannelsBadges#3]
hi,
there seems to be an issue with the "icons"
https://i.imgur.com/W9KdGRP.png
https://i.imgur.com/cc7dCvM.png

**Comment by thehamish555** [comment]
how do these emoji's load for you?

```
            { svgContent: [VOICE, VOICE_CUT], className1: 'voiceTags-2408cb', className2: 'voiceTags-2409cb', tagName: 'VOICE', emoji: '🎤', secureEmoji: '🔒', warnTag: VOICE_WARN, secureTag: VOICE_SECU },
            { svgContent: [FORUM, FORUM_CUT], className1: 'forumTags-2408cb', className2: 'forumTags-2409cb', tagName: 'FORUM', emoji: '📰', secureEmoji: '🔒', warnTag: FORUM_WARN, secureTag: FORUM_SECU },
            { svgContent: [ADS, ADS_CUT, ADS_CUT_W], className1: 'adsTags-2408cb', className2: 'adsTags-2409cb', tagName: 'ADS', emoji: '📝', secureEmoji: '🔒', warnTag: ADS_WARN, secureTag: ADS_SECU },
            { svgContent: [RULE], className1: 'ruleTags-2408cb', className2: 'ruleTags-2409cb', tagName: 'RULE', emoji: '📋' },
            { svgContent: [NSFW], className1: 'nsfwTags-2408cb', className2: 'nsfwTags-2409cb', tagName: 'NSFW', emoji: '🔞' },
```
what you should see in the code block is 🎤🔒📰📝📋🔞 spread throughout. If you cant, its possible that your computer doesnt support the emojis or something on discord is breaking it, because the icons are simply emojis

**Comment by AcesGamingUK** [comment]
> how do these emoji's load for you?
> 
> ```
> { svgContent: [VOICE, VOICE_CUT], className1: 'voiceTags-2408cb', className2: 'voiceTags-2409cb', tagName: 'VOICE', emoji: '🎤', secureEmoji: '🔒', warnTag: VOICE_WARN, secureTag: VOICE_SECU },
> { svgContent: [FORUM, FORUM_CUT], className1: 'forumTags-2408cb', className2: 'forumTags-2409cb', tagName: 'FORUM', emoji: '📰', secureEmoji: '🔒', warnTag: FORUM_WARN, secureTag: FORUM_SECU },
> { svgContent: [ADS, ADS_CUT, ADS_CUT_W], className1: 'adsTags-2408cb', className2: 'adsTags-2409cb', tagName: 'ADS', emoji: '📝', secureEmoji: '🔒', warnTag: ADS_WARN, secureTag: ADS_SECU },
> { svgContent: [RULE], className1: 'ruleTags-2408cb', className2: 'ruleTags-2409cb', tagName: 'RULE', emoji: '📋' },
> { svgContent: [NSFW], className1: 'nsfwTags-2408cb', className2: 'nsfwTags-2409cb', tagName: 'NSFW', emoji: '🔞' },
> ```
> 
> what you should see in the code block is 🎤🔒📰📝📋🔞 spread throughout. If you cant, its possible that your computer doesnt support the emojis or something on discord is breaking it, because the icons are simply emojis

for me they were not showing inside the file, must have broke when i updated BD somehow, 
replacing them with the lines above fixed the issue

**Comment by thehamish555** [comment]
> for me they were not showing inside the file, must have broke when i updated BD somehow,
replacing them with the lines above fixed the issue

It may be best to just copy and paste the entire .js file again because there are several more emojis throughout (like on the settings page)

**Comment by SheiylaDev** [comment]
Hello, the plugin is being changed with new features and a complete restructuring.
